var tipuesearch = {"pages": [
                                    { "title": "Complex Parliaments in Transition", "text": "Complex Parliaments in Transition", "tags": "", "loc": "ojs133-article.html#ojs133-head1" },
{ "title": "Complex Parliaments in Transition", "text": "Central European Federations Facing Regime Change", "tags": "", "loc": "ojs133-article.html#ojs133-head2" },
{ "title": "Complex Parliaments in Transition", "text": "What is a socialist parliament? This is a question that many political historians may see as redundant or pointless. Parliaments in the one-party socialist states in the Eastern Europe after World War II are frequently shrugged off with an effortless explanation that they were merely façades of the socialist regimes. Although this cannot be completely refuted, questions nevertheless arise in the modern political historiography, calling for answers stemming from the neo-institutionalist paradigm. What were the socialist parliaments like? How were they organised? What was their outward appearance, who were their members, how did they operate, what sorts of mechanisms guided the socialist parliamentarism, and so on? At least a few members of the European Information and Research Network on Parliamentary History (EuParl.net), which brings together research organisations focusing on the history of parliamentarism, deal with this phenomenon systematically. These efforts resulted in the idea to organise a workshop where these researchers could exchange their outlooks on socialist parliaments in their terminal stages, when they were already undergoing a transformation into modern European parliaments.", "tags": "", "loc": "ojs133-article.html#ojs133-p-1" },
{ "title": "Complex Parliaments in Transition", "text": "The workshop was organised by the Institute of Contemporary History in Ljubljana in cooperation with the Czech Institute for Contemporary History (Ústav pro soudobé dějiny AV ČR) from Prague and the Commission for the History of Parliamentarianism and Political Parties (Kommission für Geschichte des Parlamentarismus und der politischen Parteien) from Berlin. It took place on 16 October 2015 in Ljubljana at the Institute of Contemporary History, in the building where in the past – until 1959 – the Socialist Parliament of the Republic of Slovenia had held its sessions.", "tags": "", "loc": "ojs133-article.html#ojs133-p-2" },
{ "title": "Complex Parliaments in Transition", "text": "The main idea and purpose of the gathering was to illustrate the transformation of the parliaments and parliamentary systems in the late 1980s and early 1990s. We did not want to define any detailed programme points – deliberately, because we wanted the academic space for our workshop to remain as open as possible.", "tags": "", "loc": "ojs133-article.html#ojs133-p-3" },
{ "title": "Complex Parliaments in Transition", "text": "In the introduction only a few common points were defined: The collapse of the socialist regimes in 1989-1990 set off multifaceted processes of democratic reforms as well as social and economic transformations. In some of the East-Central European countries, these transformations were even more complex due to their federal structure. Originally, the Yugoslav and Czechoslovak federal systems had been intended to engineer a socialist equality of the member nations. However, following the changes in the late 1980s, this basic precondition ceased to exist and the various parts of the federations began to express interests, use powers, build party systems and create ethnic publics.", "tags": "", "loc": "ojs133-article.html#ojs133-p-4" },
{ "title": "Complex Parliaments in Transition", "text": "The workshop explored some of these examples in detail, by comparing the transformations of the parliamentary systems in three federal countries in the early 1990s – in Czechoslovakia, Yugoslavia and Germany. In Czechoslovakia, the strong legal continuity between the socialist, revolutionary and post-socialist era created fascinating blends of the three images of parliament. The German case is described through the colonisation metaphor, which is interesting to test on the example of the East German Volkskammer. In Yugoslavia, where the already loose federal system kept getting looser, the individual federal republics with their own socialist parliaments eventually became the only truly important political actors in the process of system and state disintegration.", "tags": "", "loc": "ojs133-article.html#ojs133-p-5" },
{ "title": "Complex Parliaments in Transition", "text": "* * *", "tags": "", "loc": "ojs133-article.html#ojs133-ab-1" },
{ "title": "Complex Parliaments in Transition", "text": "Already during the preparations for the workshop one of the ambitions of the organisers was to collect some of the contributions and discussions as well as the results of the research projects and publish them in a special topical issue of our scholarly journal, thus making them available for the scrutiny or challenge of the scholarly and general public. The ambition ultimately resulted in this special issue of the Contributions to Contemporary History (Prispevki za novejšo zgodovino) journal. The issue includes six scientific articles on the topic of Complex Parliaments in Transition: Central European Federations Facing Regime Change. It also includes two reports from the scientific conferences on the history of parliamentarism (from the workshop Complex Parliaments in Transition and the conference Parlamentarismuskritik und Antiparlamentarismus in Europa, which took place in May 2015 in Berlin, also under the umbrella of the EuParl.net) as well as the presentation of the posthumously published study on the Austrian Parliament – the Vienna Reichsrat and Slovenians in the time of the Habsburg Monarchy.", "tags": "", "loc": "ojs133-article.html#ojs133-p-6" },
{ "title": "Complex Parliaments in Transition", "text": "All of these contributions undoubtedly demonstrate the complexity of the issue at hand, as well as open and completely convincingly close numerous questions. Besides the specific characteristics of the individual states that they focus on (Czechoslovakia, Germany, Yugoslavia/Slovenia), these contributions also exhibit differences in the intensity of research and approaches in the context of individual national historiographies.", "tags": "", "loc": "ojs133-article.html#ojs133-p-7" }

                     ]};
                